import uuid
from sqlmodel import Field, Relationship, SQLModel, String

from enums.course import CourseCategory
from models import register_model
from models.university import University

@register_model
class Course(SQLModel, table=True, extra="ignore"):
    id: uuid.UUID = Field(
            primary_key=True,
            index=True,
            nullable=False,
            description="Primary key as UUID4, generated by the backend, not the db"
            )
    uni_id: int = Field(
            ...,
            foreign_key="university.id",
            ondelete="CASCADE"
            )
    university: University = Relationship(
            back_populates="courses"
            )
    is_summer: bool = Field(...)
    name: str = Field(...)
    ects: int = Field(...)
    category: CourseCategory = Field(
            sa_type=String,
            nullable=False
            )
