from enum import StrEnum


class Country(StrEnum):
    # EU Member States (27)
    AUSTRIA = "AUSTRIA"
    BELGIUM = "BELGIUM"
    BULGARIA = "BULGARIA"
    CROATIA = "CROATIA"
    CYPRUS = "CYPRUS"
    CZECH_REPUBLIC = "CZECH REPUBLIC"
    DENMARK = "DENMARK"
    ESTONIA = "ESTONIA"
    FINLAND = "FINLAND"
    FRANCE = "FRANCE"
    GERMANY = "GERMANY"
    GREECE = "GREECE"
    HUNGARY = "HUNGARY"
    IRELAND = "IRELAND"
    ITALY = "ITALY"
    LATVIA = "LATVIA"
    LITHUANIA = "LITHUANIA"
    LUXEMBOURG = "LUXEMBOURG"
    MALTA = "MALTA"
    NETHERLANDS = "NETHERLANDS"
    POLAND = "POLAND"
    PORTUGAL = "PORTUGAL"
    ROMANIA = "ROMANIA"
    SLOVAKIA = "SLOVAKIA"
    SLOVENIA = "SLOVENIA"
    SPAIN = "SPAIN"
    SWEDEN = "SWEDEN"
    
    # Non-EU Program Countries
    NORTH_MACEDONIA = "NORTH MACEDONIA"
    SERBIA = "SERBIA"
    ICELAND = "ICELAND"
    LIECHTENSTEIN = "LIECHTENSTEIN"
    NORWAY = "NORWAY"
    TURKEY = "TURKEY"  # Officially listed as "Türkiye" in Erasmus+, but using common English name
